Update shell script style

diff --git a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
--- a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
+++ b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
@@ -17,6 +17,8 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+set -euo pipefail
+
 FRIENDLY_NAME="Neo4j Server"
 
 function findBaseDirAndCdThere {
@@ -24,27 +26,27 @@ function findBaseDirAndCdThere {
 # is the case, it should be fixed to be so, if possible.
   SCRIPT=$0
 
-  cd "`dirname "$SCRIPT"`"
-  SCRIPT=`basename "$SCRIPT"`
+  cd "$(dirname "${SCRIPT}")"
+  SCRIPT="$(basename "${SCRIPT}")"
 
-  while [ -L "$SCRIPT" ]
+  while [ -L "${SCRIPT}" ]
   do
-    SCRIPT=$( readlink "$SCRIPT" )
-    cd "$(dirname "$SCRIPT")"
-    SCRIPT=`basename "$SCRIPT"`
+    SCRIPT="$(readlink "${SCRIPT}")"
+    cd "$(dirname "${SCRIPT}")"
+    SCRIPT="$(basename "${SCRIPT}")"
   done
-  NEO4J_HOME=`cd $( dirname "$SCRIPT" )/.. && dirs -l +0`
-  NEO4J_INSTANCE=$NEO4J_HOME
-  [ -n "$NEO4J_CONFIG" ] || NEO4J_CONFIG=$NEO4J_HOME/conf
-  [ -n "$NEO4J_LOG" ] || NEO4J_LOG=$NEO4J_HOME/data/log
-  [ -n "$NEO4J_PIDFILE" ] || NEO4J_PIDFILE=$NEO4J_HOME/data/neo4j-service.pid
+  NEO4J_HOME="$(cd "$(dirname "${SCRIPT}")/.." && dirs -l +0)"
+  NEO4J_INSTANCE="${NEO4J_HOME}"
+  [[ "${NEO4J_CONFIG:-}" ]] || NEO4J_CONFIG="${NEO4J_HOME}/conf"
+  [[ "${NEO4J_LOG:-}" ]] || NEO4J_LOG="${NEO4J_HOME}/data/log"
+  [[ "${NEO4J_PIDFILE:-}" ]] || NEO4J_PIDFILE="${NEO4J_HOME}/data/neo4j-service.pid"
 
-  cd "$NEO4J_HOME"
+  cd "${NEO4J_HOME}"
 }
 
 function parseConfig {
-  if [ ${BASH_VERSINFO[0]} -eq 3 ] ; then
-    if [ ${BASH_VERSINFO[1]} -lt 2 ] ; then
+  if [ "${BASH_VERSINFO[0]}" -eq 3 ] ; then
+    if [ "${BASH_VERSINFO[1]}" -lt 2 ] ; then
       getconfigquoted "${NEO4J_CONFIG}/neo4j-wrapper.conf"
       getconfigquoted "${NEO4J_CONFIG}/neo4j-server.properties"
       return
@@ -58,51 +60,55 @@ findBaseDirAndCdThere
 source bin/utils
 parseConfig
 
-JAVA_OPTS="-server -XX:+DisableExplicitGC ${wrapper_java_additional}"
-[ -z "${wrapper_java_initmemory}" ] || JAVA_OPTS="$JAVA_OPTS -Xms${wrapper_java_initmemory}m"
-[ -z "${wrapper_java_maxmemory}" ] || JAVA_OPTS="$JAVA_OPTS -Xmx${wrapper_java_maxmemory}m"
+JAVA_OPTS="-server -XX:+DisableExplicitGC"
+[[ "${wrapper_java_additional:-}" ]] && JAVA_OPTS="${JAVA_OPTS} ${wrapper_java_additional}"
+[[ "${wrapper_java_initmemory:-}" ]] && JAVA_OPTS="${JAVA_OPTS} -Xms${wrapper_java_initmemory}m"
+[[ "${wrapper_java_maxmemory:-}" ]] && JAVA_OPTS="${JAVA_OPTS} -Xmx${wrapper_java_maxmemory}m"
 
 NEO4J_SERVER_PORT="${org_neo4j_server_webserver_port:=7474}"
 NEO4J_SERVER_ADDRESS="${org_neo4j_server_webserver_address:=localhost}"
 TIMEOUT=120
-PID_FILE=${NEO4J_PIDFILE}
+PID_FILE="${NEO4J_PIDFILE}"
 
 buildclasspath() {
-  LIBDIR="$NEO4J_HOME"/lib
-  if [ ! -e "$LIBDIR" ] ; then
-    echo "Error: missing Neo4j Library, expected at $LIBDIR"
+  LIBDIR="${NEO4J_HOME}/lib"
+  if [ ! -e "${LIBDIR}" ] ; then
+    echo "Error: missing Neo4j Library, expected at ${LIBDIR}"
     exit 1
   fi
 
-  SYSLIBDIR="$NEO4J_HOME"/system/lib
-  if [ ! -e "$SYSLIBDIR" ] ; then
-    echo "Error: missing Neo4j System Library, expected at $SYSLIBDIR"
+  SYSLIBDIR="${NEO4J_HOME}/system/lib"
+  if [ ! -e "${SYSLIBDIR}" ] ; then
+    echo "Error: missing Neo4j System Library, expected at ${SYSLIBDIR}"
     exit 1
   fi
 
   ALL_JARS=""
-  for jar in "$LIBDIR"/*.jar "$SYSLIBDIR"/*.jar ; do
-    [ -z "$ALL_JARS" ] && ALL_JARS="$jar" || ALL_JARS="$ALL_JARS":"$jar"
+  for jar in "${LIBDIR}"/*.jar "${SYSLIBDIR}"/*.jar ; do
+    if [[ "${ALL_JARS:-}" ]] ; then
+      ALL_JARS="${ALL_JARS}:"
+    fi
+    ALL_JARS="${ALL_JARS}${jar}"
   done
 
-  for jar in "$NEO4J_HOME"/plugins/*.jar ; do
-    if [ -e "$jar" ] ; then
-      ALL_JARS="$ALL_JARS":"$jar"
+  for jar in "${NEO4J_HOME}"/plugins/*.jar ; do
+    if [ -e "${jar}" ] ; then
+      ALL_JARS="${ALL_JARS}:${jar}"
     fi
   done
 
-  for jar in "$NEO4J_HOME"/plugins/**/*.jar ; do
-    if [ -e "$jar" ] ; then
-      ALL_JARS="$ALL_JARS":"$jar"
+  for jar in "${NEO4J_HOME}"/plugins/**/*.jar ; do
+    if [ -e "${jar}" ] ; then
+      ALL_JARS="${ALL_JARS}:${jar}"
     fi
   done
 
-  CLASSPATH=${ALL_JARS}
+  CLASSPATH="${ALL_JARS}"
 }
 
 startit() {
   checkstatus
-  if [ -n "${NEO4J_PID}" ] ; then
+  if [[ "${NEO4J_PID:-}" ]] ; then
     echo "${FRIENDLY_NAME} is already running (pid ${NEO4J_PID})."
     exit 0
   fi
@@ -124,7 +130,7 @@ startit() {
 
   sleep 5
   checkstatus
-  if [ -z "${NEO4J_PID}" ] ; then
+  if [[ ! "${NEO4J_PID:-}" ]] ; then
     echo "Unable to start. See ${CONSOLE_LOG} for details."
     rm "${PID_FILE}"
     exit 1
@@ -132,7 +138,7 @@ startit() {
 
   echo "Started at http://${NEO4J_SERVER_ADDRESS}:${NEO4J_SERVER_PORT} (pid ${NEO4J_PID})."
 
-  if [ "${org_neo4j_server_database_mode}" = "HA" ] ; then
+  if [ "${org_neo4j_server_database_mode:-}" = "HA" ] ; then
     echo "This HA instance will be operational once it has joined the cluster. See ${CONSOLE_LOG} for current status."
   else
     echo "There may be a short delay until the server is ready."
@@ -141,7 +147,7 @@ startit() {
 
 console() {
   checkstatus
-  if [ -n "${NEO4J_PID}" ] ; then
+  if [[ "${NEO4J_PID:-}" ]] ; then
     echo "${FRIENDLY_NAME} is already running (pid ${NEO4J_PID})."
     exit 1
   fi
@@ -165,12 +171,12 @@ showinfo() {
   exitonnojava
   buildclasspath
 
-  echo "NEO4J_HOME:        $NEO4J_HOME"
-  echo "NEO4J_SERVER_PORT: $NEO4J_SERVER_PORT"
-  echo "NEO4J_INSTANCE:    $NEO4J_INSTANCE"
-  echo "JAVA_HOME:         $JAVA_HOME"
-  echo "JAVA_OPTS:         $JAVA_OPTS"
-  echo "CLASSPATH:         $CLASSPATH"
+  echo "NEO4J_HOME:        ${NEO4J_HOME}"
+  echo "NEO4J_SERVER_PORT: ${NEO4J_SERVER_PORT}"
+  echo "NEO4J_INSTANCE:    ${NEO4J_INSTANCE}"
+  echo "JAVA_HOME:         ${JAVA_HOME}"
+  echo "JAVA_OPTS:         ${JAVA_OPTS}"
+  echo "CLASSPATH:         ${CLASSPATH}"
 }
 
 case "$1" in
diff --git a/packaging/standalone/src/main/distribution/shell-scripts/bin/utils b/packaging/standalone/src/main/distribution/shell-scripts/bin/utils
--- a/packaging/standalone/src/main/distribution/shell-scripts/bin/utils
+++ b/packaging/standalone/src/main/distribution/shell-scripts/bin/utils
@@ -33,10 +33,29 @@ function show_installation_instructions() {
 function getconfig {
   if [ -e "$1" ]; then
     while read line ; do
-      if [[ ${line} =~ ^([^#\s][^=]+)=(.+)$ ]]; then
-        key=`echo ${BASH_REMATCH[1]} | sed 's/\./_/g'`
+      if [[ "${line}" =~ ^([^#\s][^=]+)=(.+)$ ]]; then
+        key="${BASH_REMATCH[1]//./_}"
         value="${BASH_REMATCH[2]}"
-        if [[ ${key} =~ ^(.*)_([0-9]+)$ ]]; then
+        if [[ "${key}" =~ ^(.*)_([0-9]+)$ ]]; then
+          key="${BASH_REMATCH[1]}"
+        fi
+        if [[ "${!key:-}" ]]; then
+          export ${key}="${!key} ${value}"
+        else
+          export ${key}="$value"
+        fi
+      fi
+    done <"$1"
+  fi
+}
+
+function getconfigquoted {
+  if [ -e "$1" ]; then
+    while read line ; do
+      if [[ "${line}" =~ "^([^#\s][^=]+)=(.+)$" ]]; then
+        key="${BASH_REMATCH[1]//./_}"
+        value="${BASH_REMATCH[2]}"
+        if [[ "${key}" =~ "^(.*)(_[0-9]+)?$" ]]; then
           key="${BASH_REMATCH[1]}"
         fi
         if [[ ${!key} ]]; then
@@ -45,26 +64,7 @@ function getconfig {
           export ${key}="$value"
         fi
       fi
-    done < "$1"
-  fi
-}
-
-function getconfigquoted {
-  if [ -e "$1" ]; then
-    while read line ; do
-      if [[ ${line} =~ "^([^#\s][^=]+)=(.+)$" ]]; then
-        key=`echo ${BASH_REMATCH[1]} | sed 's/\./_/g'`
-        value="${BASH_REMATCH[2]}"
-        if [[ ${key} =~ "^(.*)(_[0-9]+)?$" ]]; then
-          key=${BASH_REMATCH[1]}
-        fi
-        if [[ ${!key} ]]; then
-          export ${key}="${!key} ${value}"
-        else
-          export ${key}="$value"
-        fi
-      fi
-    done < "$1"
+    done <"$1"
   fi
 }
 
@@ -72,50 +72,50 @@ function getconfigquoted {
 findjava() {
   detectos
   if [ "${DIST_OS}" == "macosx" ] ; then
-     if [ -z "$JAVA_VERSION" ] ; then
+     if [[ ! "${JAVA_VERSION:-}" ]] ; then
        JAVA_VERSION="CurrentJDK"
      else
-       echo "Using Java version: $JAVA_VERSION"
+       echo "Using Java version: ${JAVA_VERSION}"
      fi
-     if [ -z "$JAVA_HOME" ] ; then
-       JAVA_HOME=`/usr/libexec/java_home -v 1.8`
+     if [[ ! "${JAVA_HOME:-}" ]] ; then
+       JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
      fi
   fi
 
-  if [ -z "$JAVA_HOME" ] ; then
+  if [[ ! "${JAVA_HOME:-}" ]] ; then
     if [ -r /etc/gentoo-release ] ; then
-      JAVA_HOME=`java-config --jre-home`
+      JAVA_HOME="$(java-config --jre-home)"
     fi
   fi
 
   if [ "${DIST_OS}" == "cygwin" ] ; then
     # ensure paths are in UNIX format
-    [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
-    [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
+    [ -n "${JAVA_HOME}" ] && JAVA_HOME="$(cygpath --unix "${JAVA_HOME}")"
+    [ -n "${CLASSPATH}" ] && CLASSPATH="$(cygpath --path --unix "${CLASSPATH}")"
   fi
 
   # If a specific java binary isn't specified search for the standard 'java' binary
-  if [ -z "$JAVACMD" ] ; then
-    if [ -n "$JAVA_HOME"  ] ; then
-      if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+  if [[ ! "${JAVACMD:-}" ]] ; then
+    if [[ "${JAVA_HOME:-}" ]] ; then
+      if [ -x "${JAVA_HOME}/jre/sh/java" ] ; then
         # IBM's JDK on AIX uses strange locations for the executables
-        JAVACMD="$JAVA_HOME/jre/sh/java"
+        JAVACMD="${JAVA_HOME}/jre/sh/java"
       else
-        JAVACMD="$JAVA_HOME/bin/java"
+        JAVACMD="${JAVA_HOME}/bin/java"
       fi
     else
       if [ "${DIST_OS}" != "macosx" ] ; then
         # Don't use default java on Darwin because it displays a misleading dialog box
-        JAVACMD=`which java`
+        JAVACMD="$(which java)"
       fi
     fi
   fi
 }
 
 checkstatus() {
-  if [ -e "$PID_FILE" ] ; then
-    NEO4J_PID=$( cat "$PID_FILE" )
-    kill -0 $NEO4J_PID 2>/dev/null || NEO4J_PID=""
+  if [ -e "${PID_FILE}" ] ; then
+    NEO4J_PID=$( cat "${PID_FILE}" )
+    kill -0 "${NEO4J_PID}" 2>/dev/null || NEO4J_PID=""
   fi
 }
 
@@ -123,20 +123,20 @@ reportstatus() {
   checkstatus
   exitonnojava
 
-  if [ -z $NEO4J_PID ] ; then
-    echo "$FRIENDLY_NAME is not running"
+  if [[ ! "${NEO4J_PID:-}" ]] ; then
+    echo "${FRIENDLY_NAME} is not running"
   	exit 3
   else
-    echo "$FRIENDLY_NAME is running at pid $NEO4J_PID"
+    echo "${FRIENDLY_NAME} is running at pid ${NEO4J_PID}"
   fi
 }
 
-# Use findjava to set JAVACMD. If that fails ($JAVACMD is not set) then exit with failure
+# Use findjava to set JAVACMD. If that fails (${JAVACMD} is not set) then exit with failure
 exitonnojava() {
   findjava
 
-  if [ ! -x "$JAVACMD" ] ; then
-    echo "ERROR: Unable to find java. (Cannot execute $JAVACMD)"
+  if [ ! -x "${JAVACMD}" ] ; then
+    echo "ERROR: Unable to find java. (Cannot execute ${JAVACMD})"
     show_java_requirements
     show_installation_instructions
     exit 1
@@ -145,13 +145,16 @@ exitonnojava() {
 
 # Resolve the os
 detectos() {
-  DIST=`uname -s | tr 'A-Z' 'a-z' | tr -d ' '`
-  case "$DIST" in
+  DIST="$(uname -s | tr 'A-Z' 'a-z' | tr -d ' ')"
+  case "${DIST}" in
     'darwin')
       DIST_OS="macosx"
       ;;
     'cygwin')
       DIST_OS="cygwin"
+      ;;
+    *)
+      DIST_OS="other"
       ;;
   esac
 }
@@ -159,32 +162,32 @@ detectos() {
 stopit() {
   checkstatus
 
-  if [ -z $NEO4J_PID ] ; then
-    echo "ERROR: $FRIENDLY_NAME not running"
-    [ -e "$PID_FILE" ] && rm "$PID_FILE"
+  if [[ ! "${NEO4J_PID:-}" ]] ; then
+    echo "ERROR: ${FRIENDLY_NAME} not running"
+    [ -e "${PID_FILE}" ] && rm "${PID_FILE}"
   else
-    printf "Stopping $FRIENDLY_NAME [$NEO4J_PID]..."
+    echo -n "Stopping ${FRIENDLY_NAME} [${NEO4J_PID}]..."
     x=0
-    while [ "$NEO4J_PID" != "" ]  ; do
-      kill $NEO4J_PID 2>/dev/null
-      if [ $x -le $TIMEOUT ]; then
+    while [ "${NEO4J_PID}" != "" ]  ; do
+      kill ${NEO4J_PID} 2>/dev/null
+      if [ $x -le "$TIMEOUT" ]; then
         printf "."
       fi
       sleep 1
       checkstatus
 
-      if [ $x -eq $TIMEOUT ] ;then
+      if [ $x -eq "$TIMEOUT" ] ;then
 	    echo ""
-	    echo "$FRIENDLY_NAME [$NEO4J_PID] is taking more than ${TIMEOUT}s to stop"
-	    echo "There might be some troubles with the shutdown of $FRIENDLY_NAME, please read log files for details"
-	    echo "This script will keep waiting for the server to shutdown, you could manually kill the process $NEO4J_PID"
+	    echo "${FRIENDLY_NAME} [${NEO4J_PID}] is taking more than ${TIMEOUT}s to stop"
+	    echo "There might be some troubles with the shutdown of ${FRIENDLY_NAME}, please read log files for details"
+	    echo "This script will keep waiting for the server to shutdown, you could manually kill the process ${NEO4J_PID}"
 	    echo ""
       fi
 
-      x=$[$x+1]
+      x=$((x+1))
     done
     echo " done"
-    [ -e "$PID_FILE" ] && rm  "$PID_FILE"
+    [ -e "${PID_FILE}" ] && rm  "${PID_FILE}"
   fi
 }
 
@@ -192,9 +195,9 @@ stopit() {
 # in place.
 checkandrepairenv() {
     # Create log directory if missing, change owner if created.
-    if [ ! -d "$NEO4J_LOG" ]; then
+    if [ ! -d "${NEO4J_LOG}" ]; then
       echo "${NEO4J_LOG} was missing, recreating..."
-      mkdir "$NEO4J_LOG"
+      mkdir "${NEO4J_LOG}"
     fi
 }
 
@@ -202,10 +205,10 @@ checkandrepairenv() {
 checklimits() {
   detectos
   if [ $DIST_OS != "macosx" ] ; then
-    OPEN_FILES=`ulimit -n`
+    OPEN_FILES="$(ulimit -n)"
 
-    if [ $OPEN_FILES -lt 40000 ]; then
-      echo "WARNING: Max $OPEN_FILES open files allowed, minimum of 40 000 recommended. See the Neo4j manual."
+    if [ "${OPEN_FILES}" -lt 40000 ]; then
+      echo "WARNING: Max ${OPEN_FILES} open files allowed, minimum of 40 000 recommended. See the Neo4j manual."
     fi
   fi
 }
@@ -217,7 +220,7 @@ warn_about_java_runtime() {
 }
 
 complain_about_java_version() {
-  echo "ERROR! Neo4j cannot be started using java version $JAVAVERSION. "
+  echo "ERROR! Neo4j cannot be started using java version ${JAVAVERSION}. "
   show_java_requirements
   show_installation_instructions
 }
@@ -225,20 +228,18 @@ complain_about_java_version() {
 # check if running Oracle JDK 8 or OpenJDK 8, warn if not
 checkjvmcompatibility() {
   # Shut down if java version < 1.8
-  JAVAVERSION=$("$JAVACMD" -version 2>&1 | awk -F '"' '/version/ {print $2}')
-  if [[ "$JAVAVERSION" < "1.8" ]]; then
+  JAVAVERSION=$("${JAVACMD}" -version 2>&1 | awk -F '"' '/version/ {print $2}')
+  if [[ "${JAVAVERSION}" < "1.8" ]]; then
     complain_about_java_version
     exit 1
   fi
 
-  $JAVACMD -version 2>&1 | egrep -q "(Java HotSpot\\(TM\\)|OpenJDK) (64-Bit Server|Server|Client) VM"
-  if [ $? -eq 1 ]
-  then
+  if ! ("${JAVACMD}" -version 2>&1 | egrep -q "(Java HotSpot\\(TM\\)|OpenJDK) (64-Bit Server|Server|Client) VM"); then
     warn_about_java_runtime
   fi
 }
 
 checkclasspath() {
-  echo $CLASSPATH | egrep -q 'neo4j-kernel-[0-9.]{2,8}-SNAPSHOT' && \
-  echo -e "\nWARNING! Latest Development Build. Not intended for general-purpose use. May be unstable."
+  echo "${CLASSPATH}" | egrep -q 'neo4j-kernel-[0-9.]{2,8}-SNAPSHOT' && \
+    echo -e "\nWARNING! Latest Development Build. Not intended for general-purpose use. May be unstable."
 }
