Neo4j coordinator now enjoys the same additions in its script as the server does plus the ability to be installed as a service on MacOS

diff --git a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-coordinator b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-coordinator
--- a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-coordinator
+++ b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-coordinator
@@ -1,8 +1,8 @@
 #!/bin/bash
 ### BEGIN INIT INFO
 # Provides:          neo4j-coord
-# Required-Start:     
-# Required-Stop:      
+# Required-Start:
+# Required-Stop:
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 ### END INIT INFO
@@ -33,10 +33,10 @@
 #     into a single environment variable named KEY
 function getconfig {
   if [ -e $1 ]; then
-    while read line; do 
+    while read line; do
       if [[ ${line} =~ ^([^#\s][^=]+)=(.+)$ ]]; then
         key=`echo ${BASH_REMATCH[1]} | sed 's/\./_/g'`
-        value="${BASH_REMATCH[2]}" 
+        value="${BASH_REMATCH[2]}"
         if [[ ${key} =~ ^(.*)_([0-9]+)$ ]]; then
           key=${BASH_REMATCH[1]}
           if [[ ${!key} ]]; then
@@ -51,10 +51,12 @@ function getconfig {
 
     done < $1
   fi
-}  
+}
 
 COORD_SCRIPT=$0
-[ -L "$COORD_SCRIPT" ] && COORD_SCRIPT=$( readlink $COORD_SCRIPT ) 
+while [ -L "$COORD_SCRIPT" ] ; do
+  COORD_SCRIPT=$( readlink $COORD_SCRIPT )
+done
 NEO4J_HOME=`cd $( dirname $COORD_SCRIPT )/.. && dirs -l +0`
 NEO4J_INSTANCE=$NEO4J_HOME
 cd $NEO4J_HOME
@@ -122,7 +124,11 @@ findjava() {
       JAVACMD=`which java`
     fi
   fi
+}
 
+# Use findjava to set JAVACMD. If that fails ($JAVACMD is not set) then exit with failure
+exitonnojava() {
+  findjava
   if [ ! -x "$JAVACMD" ] ; then
     echo "Error: JAVA_HOME is not defined correctly."
     echo "  We cannot execute $JAVACMD"
@@ -188,9 +194,48 @@ checkstatus() {
   fi
 }
 
+checkwriteaccess() {
+    if [ $UID != 0 ] ; then
+    if [ ! -w $NEO4J_INSTANCE/data ] ; then
+      echo "ERROR: No write access to data/ directory, run either as user $NEO4J_USER or root"
+      exit 1
+    fi
+    fi
+}
+
+getlaunchdpid() {
+  LAUNCHDPID=$(launchctl list | grep org.neo4j.coord | cut -f 1)
+  if [ -z $LAUNCHDPID ] ; then
+    # Not there
+    LAUNCHDPID=-1
+  elif [ $LAUNCHDPID = "-" ] ; then
+    # There but not running
+    LAUNCHDPID=0
+  else
+    # There and running
+    LAUNCHDPID=$(($LAUNCHDPID))
+  fi
+    
+}
+
 startit() {
 
+  exitonnojava
+  checkwriteaccess
   checkstatus
+
+  if [[ $DIST_OS -eq "macosx" ]] ; then
+    getlaunchdpid
+    if [ $LAUNCHDPID -eq 0 ] ; then
+      echo "Detected installation in launchd, starting it..."
+      launchctl start org.neo4j.coord
+      exit 0
+    elif [ $LAUNCHDPID -gt 0 ] ; then
+      echo "Instance already running via launchd with PID $LAUNCHDPID"
+      exit 1
+    fi
+    # We fall through here since if there is no launchd install we start manually
+  fi
 
   if [ -z $NEO4J_PID ] ; then
     printf "Starting neo4j-coord..."
@@ -207,7 +252,7 @@ startit() {
     fi
     STARTED_PID=$( cat $PID_FILE )
 
-    printf " process [$STARTED_PID]... waiting for server to be ready."
+    printf " process [$STARTED_PID]... waiting for coordinator to be ready."
 
     if kill -0 $STARTED_PID 2>/dev/null ; then
       echo " OK."
@@ -215,11 +260,11 @@ startit() {
     fi
 
     echo " BAD."
-    echo "Server may have failed to start, please check the logs."
+    echo "Coordinator may have failed to start, please check the logs."
     rm $PID_FILE
     exit 1
   else
-    echo "Server already running with pid $NEO4J_PID"
+    echo "Coordinator already running with pid $NEO4J_PID"
     exit 1
   fi
 }
@@ -228,6 +273,17 @@ startit() {
 stopit() {
 
   checkstatus
+  checkwriteaccess
+  
+  if [[ $DIST_OS -eq "macosx" ]] ; then
+    getlaunchdpid
+    if [ $LAUNCHDPID -gt 0 ] ; then
+      echo "Instance running via launchd with PID $LAUNCHDPID, stopping it..."
+      launchctl stop org.neo4j.coord
+      return
+    fi
+    # We fall through here since if there is no launchd install we stop manually started instance
+  fi
 
   if [ -z $NEO4J_PID ] ; then
     echo "ERROR: coordinator not running"
@@ -248,7 +304,7 @@ stopit() {
 }
 
 reportstatus() {
- 
+
   checkstatus
 
   if [ -z $NEO4J_PID ] ; then
@@ -256,7 +312,6 @@ reportstatus() {
   else
     echo "Neo4j Coordinator is running at pid $NEO4J_PID"
   fi
-
 }
 
 console() {
@@ -266,7 +321,7 @@ console() {
   if [ -z $NEO4J_PID ] ; then
     echo "Starting neo4j coordinator console-mode..."
 
-    findjava
+    exitonnojava
     buildclasspath
 
     $JAVACMD -cp $CLASSPATH $JAVA_OPTS $NEO4J_OPTS org.apache.zookeeper.server.quorum.QuorumPeerMain conf/coord.cfg
@@ -300,14 +355,14 @@ modify_user_config() {
 
 # Creates a user on the system
 create_user() {
-  useradd -M -r $1
+  useradd -r $1
   modify_user_config $1 "true"
   echo "Created user \"${1}\"."
 }
 
 remove_user() {
   if [[ $wrapper_user_created == "true" ]]; then
-    read -p "It appears that user ${wrapper_user} was created during install. Remove that user now? [yN] " yn
+    read -p "It appears that user \"${wrapper_user}\" was created during install. Remove that user now? [yN] " yn
     case $yn in
       [Yy]* ) deluser $wrapper_user
         ;;
@@ -321,6 +376,17 @@ remove_user() {
 
 installservice() {
     detectos
+    findjava
+    if [ ! -x "$JAVACMD" ] ; then
+      read -p "It was not possible to determine JAVA_HOME. Do you want to continue with the installation? [yN]" yn
+      case $yn in
+              [yY]* ) echo "WARNING: Alright, but Neo4j Coordinator will fail to launch until Java has been properly installed and configured."
+              ;;
+      * ) echo "Aborting installation."
+          exit 1
+              ;;
+      esac
+    fi
 
     if [[ -d "/etc/init.d" ]]; then
       if [[ -e "/etc/init.d/${SERVICE_NAME}" ]]; then
@@ -353,17 +419,23 @@ installservice() {
         fi
       fi
     elif [[ $DIST_OS -eq "macosx" ]] ; then
-      sed -e "s^NEO4J_INSTANCE^${NEO4J_INSTANCE}^" <${NEO4J_INSTANCE}/bin/org.neo4j.server.plist >${LAUNCHD_DIR}/org.neo4j.server.plist
-      launchctl load -w ${LAUNCHD_DIR}/org.neo4j.server.plist
-      launchctl start org.neo4j.server
+      sed -e "s^NEO4J_INSTANCE^${NEO4J_INSTANCE}^" <${NEO4J_INSTANCE}/bin/org.neo4j.coord.plist >${LAUNCHD_DIR}/org.neo4j.coord.plist
+      launchctl load -w ${LAUNCHD_DIR}/org.neo4j.coord.plist
+      launchctl start org.neo4j.coord
     else
       echo "Sorry, don't know how to install on ${DIST_OS}."
+    fi
+
+    if [ -x "$JAVACMD" ] ; then
+      if [[ $DIST_OS -ne "macosx" ]] ; then
+        startit
+      fi
     fi
 }
 
 removeservice() {
     checkstatus
- 
+
     if [[ -d "/etc/init.d" ]]; then
       if [[ -e "/etc/init.d/${SERVICE_NAME}" ]]; then
         if [  $UID != 0 ] ; then
@@ -383,9 +455,9 @@ removeservice() {
       fi
 
     elif [[ $DIST_OS -eq "macosx" ]] ; then
-      if [[ -e ${LAUNCHD_DIR}/org.neo4j.server.plist ]]; then
-        launchctl unload -w ${LAUNCHD_DIR}/org.neo4j.server.plist
-        rm ${LAUNCHD_DIR}/org.neo4j.server.plist
+      if [[ -e ${LAUNCHD_DIR}/org.neo4j.coord.plist ]]; then
+        launchctl unload -w ${LAUNCHD_DIR}/org.neo4j.coord.plist
+        rm ${LAUNCHD_DIR}/org.neo4j.coord.plist
       fi
     else
       echo "Sorry, don't know how to install on ${DIST_OS}."
@@ -397,11 +469,10 @@ removeservice() {
 showinfo() {
   reportstatus
 
-  findjava
+  exitonnojava
   buildclasspath
 
   echo "NEO4J_HOME:        $NEO4J_HOME"
-  echo "NEO4J_SERVER_PORT: $NEO4J_SERVER_PORT"
   echo "NEO4J_INSTANCE:    $NEO4J_INSTANCE"
   echo "JAVA_HOME:         $JAVA_HOME"
   echo "JAVA_OPTS:         $JAVA_OPTS"
