Remove wait after start from Unix script
This functionality has long been problematic for three reasons.

* It uses lsof which is an endless cause of compatibility bugs because
  its interface changes across distributions and verions.
* It doesn't actually work as intended. The expectation is that the
  server is ready to serve requests when the script exits. In fact that
  is not quite the case because Jetty has this weird behaviour where it
  binds the port before the handler is actually ready. So using "port
  bound" as a proxy for "ready" doesn't work.
* It takes a massively simplistic view of what it means for Neo4j to be
  "ready". It doesn't take into account the complexity of recovery,
  upgrades or clustering; each of which can make the server unavailable
  even though the port is bound.

We are losing functionality here because errors early in the DBMS
lifecycle may not be repoorted. Probably the biggest loss is in the case
when there is something else listening on the same port. Previously we
attempted to catch that in the shell script and give a clear message but
now the user will have to look in the logs find the information they
need.

In fact even this latter is not as simple as it looks since, following
the changes for Bolt, it's now possible for the DBMS to be running
perfectly happily with nothing listening on port 7474.

We hope to introduce mitigation for this loss later. Either have
something that polls real endpoints (e.g. curl), although it's not clear
how that would work in the Bolt-only case; or modify the DMBS so that it
can signal back to the parent process that it's up and happy.

As a temporary measure we are sleeping for five seconds after starting
the process and checking that it's still alive. That way we can tell the
user about very early errors (e.g. port binding problems). The sleep
time has been chosen experimentally and we can't be sure that it will
always be long enough.

diff --git a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
--- a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
+++ b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
@@ -63,8 +63,8 @@ JAVA_OPTS="-server -XX:+DisableExplicitGC ${wrapper_java_additional}"
 [ -z "${wrapper_java_initmemory}" ] || JAVA_OPTS="$JAVA_OPTS -Xms${wrapper_java_initmemory}m"
 [ -z "${wrapper_java_maxmemory}" ] || JAVA_OPTS="$JAVA_OPTS -Xmx${wrapper_java_maxmemory}m"
 
-NEO4J_SERVER_PORT=${org_neo4j_server_webserver_port:=7474}
-
+NEO4J_SERVER_PORT="${org_neo4j_server_webserver_port:=7474}"
+NEO4J_SERVER_ADDRESS="${org_neo4j_server_webserver_address:=localhost}"
 TIMEOUT=120
 
 PID_FILE=${NEO4J_PIDFILE}
@@ -101,105 +101,43 @@ buildclasspath() {
   CLASSPATH=${ALL_JARS}
 }
 
-detectrunning() {
-  if [ $DIST_OS = "solaris" ] ; then
-    ## SmartOS has a different lsof command line arguments
-    newpid=$(lsof -o $NEO4J_SERVER_PORT | grep '::' | head -n1 | cut -d ' ' -f 1)
-  else
-    LSOFVER=$(lsof -v 2>&1 | grep revision | grep -v latest | cut -d: -f2 | tr -d ' ' | tr -d .)
-    #Newer versions of lsof has the -sTCP:LISTEN flag, which is exactly what we need.
-    #This flag does not exist before 4.78, therefore grepping for TST=LISTEN worked there.
-    #Only in 4.89 did grepping begin to not work, as the output from lsof changed.
-    if [ "$LSOFVER" -ge 478 ]; then
-      newpid=$(lsof -i :"$NEO4J_SERVER_PORT" -sTCP:LISTEN -t)
-    else
-      newpid=$(lsof -i :"$NEO4J_SERVER_PORT" -F T -Ts | grep -i "TST=LISTEN" -B1 | head -n1)
-      newpid=${newpid:1}
-    fi
-  fi
-}
-
 startit() {
-  detectos
-  exitonnojava
   checkstatus
-  checklimits
+  if [ -n "${NEO4J_PID}" ] ; then
+    echo "${FRIENDLY_NAME} is already running (pid ${NEO4J_PID})."
+    exit 0
+  fi
 
+  exitonnojava
   checkjvmcompatibility
 
-  detectrunning
-  if [ $newpid ] ; then
-	     echo "Another server-process is running with [$newpid], cannot start a new one. Exiting."
-	     exit 2;
+  echo "Starting ${FRIENDLY_NAME}."
+
+  detectos
+  checklimits
+  buildclasspath
+  checkclasspath
+  checkandrepairenv
+
+  CONSOLE_LOG="${NEO4J_LOG}/console.log"
+  "${JAVACMD}" -cp "${CLASSPATH}" ${JAVA_OPTS} -Dneo4j.home="${NEO4J_HOME}" -Dfile.encoding=UTF-8 "#{neo4j.mainClass}" \
+    >>"${CONSOLE_LOG}" 2>&1 &
+  echo "$!" >"${PID_FILE}"
+
+  sleep 5
+  checkstatus
+  if [ -z "${NEO4J_PID}" ] ; then
+    echo "Unable to start. See ${CONSOLE_LOG} for details."
+    rm "$PID_FILE"
+    exit 1
   fi
 
-  if [ -z $NEO4J_PID ] ; then
-    printf "Starting $FRIENDLY_NAME..."
+  echo "Started at http://${NEO4J_SERVER_ADDRESS}:${NEO4J_SERVER_PORT} (pid ${NEO4J_PID})."
 
-    buildclasspath
-    checkclasspath
-    checkandrepairenv
-
-    CONSOLE_LOG="$NEO4J_LOG/console.log"
-
-    "$JAVACMD" -cp "${CLASSPATH}" $JAVA_OPTS  \
-      -Dneo4j.home="${NEO4J_HOME}" \
-      -Dfile.encoding=UTF-8 \
-      #{neo4j.mainClass} >> "${CONSOLE_LOG}" 2>&1 & echo $! > "${PID_FILE}"
-
-    STARTED_PID=$( cat "$PID_FILE" )
-
-    if [ "$org_neo4j_server_database_mode" = "HA" ] ; then
-      if kill -0 $STARTED_PID 2>/dev/null ; then
-        echo "HA instance started in process [$STARTED_PID]. Will be operational once connected to peers. See ${CONSOLE_LOG} for current status."
-        exit 0
-      else
-        echo "HA instance was unable to start. See ${CONSOLE_LOG}."
-        rm "$PID_FILE"
-        exit 1
-      fi
-    fi
-
-    echo -n "process [$STARTED_PID]"
-
-	  if [ $WAIT = "true" ] ; then
-	    echo -n "... waiting for server to be ready."
-	    while kill -0 $STARTED_PID 2> /dev/null ; do
-	      ## wait for start, pick up the server listening on the port
-	      detectrunning
-	      if [ $newpid ] ; then
-	         break
-	      fi
-
-	      printf "."
-	      sleep 1
-	    done
-
-	    if kill -0 $STARTED_PID 2>/dev/null ; then
-	      if [ "$newpid" != "$STARTED_PID" ] ; then
-		    rm "$PID_FILE"
-	        kill -9 $STARTED_PID
-	        echo " Failed to start within $TIMEOUT seconds."
-	        echo "$FRIENDLY_NAME failed to start, please check the logs for details."
-	        echo "If startup is blocked on a long recovery, use '$0 start-no-wait' to give the startup more time."
-	        exit 2
-	      fi
-
-	      echo " OK."
-        echo "http://localhost:$NEO4J_SERVER_PORT/ is ready."
-	      exit 0
-	    fi
-
-	    echo " Failed to start within $TIMEOUT seconds."
-	    echo "$FRIENDLY_NAME may have failed to start, please check the logs."
-	    rm "$PID_FILE"
-	    exit 1
-    else
-        echo "...Started the server in the background, returning..."
-    fi
+  if [ "${org_neo4j_server_database_mode}" = "HA" ] ; then
+    echo "This HA instance will be operational once connected to peers. See ${CONSOLE_LOG} for current status."
   else
-    echo "$FRIENDLY_NAME already running with pid $NEO4J_PID"
-    exit 0
+    echo "There may be a short delay until the server is ready."
   fi
 }
 
@@ -246,45 +184,32 @@ showinfo() {
 case "$1" in
   console)
     console
-    exit 0
     ;;
 
   start)
-    WAIT=true
     startit
-    ;;
-
-  start-no-wait)
-    WAIT=false
-    startit
-    exit 0
     ;;
 
   stop)
     stopit
-    exit 0
     ;;
 
   restart)
-    WAIT=true
     stopit
     startit
-    exit 0
     ;;
 
   status)
     reportstatus
-    exit 0
     ;;
 
   info)
     showinfo
-    exit 0
     ;;
-  *)
-    echo "Usage: neo4j { console | start | start-no-wait | stop | restart | status | info }"
-    exit 0;;
 
+  *)
+    echo "Usage: neo4j { console | start | stop | restart | status | info }"
+    ;;
 esac
 
 exit $?
