updated packaging for 1.9 - added 'arbiter' man page - added 'arbiter' debian package - removed 'coordinator' debian package - added 'arbiter' service script - removed 'coordinator' service script - fixed 'arbiter' launchd/ OSX functionality - added log4j dependency

diff --git a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-coordinator-shell b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-coordinator-shell
--- a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-coordinator-shell
+++ b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-coordinator-shell
@@ -18,5 +18,5 @@
 # You should have received a copy of the GNU Affero General Public License
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 
-echo "The Coordinator functionality and corresponding scripts are no longer required for Neo4j HA operations since version 1.9"
+echo "The Coordinator functionality and corresponding scripts are no longer required for Neo4j HA operations since version 1.9" >&2
 exit 1
