Update the arbiter script to match the main one

diff --git a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-arbiter b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-arbiter
--- a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-arbiter
+++ b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-arbiter
@@ -55,9 +55,10 @@ source bin/utils
 parseConfig
 
 JAVA_OPTS="-server ${wrapper_java_additional}"
+[ -z "${wrapper_java_initmemory}" ] || JAVA_OPTS="$JAVA_OPTS -Xms${wrapper_java_initmemory}m"
+[ -z "${wrapper_java_maxmemory}" ] || JAVA_OPTS="$JAVA_OPTS -Xmx${wrapper_java_maxmemory}m"
 
 TIMEOUT=20
-
 PID_FILE=${NEO4J_PIDFILE}
 
 buildclasspath() {
@@ -65,60 +66,57 @@ buildclasspath() {
 }
 
 startit() {
-  exitonnojava
   checkstatus
-
-  if [ -z $NEO4J_PID ] ; then
-    printf "Starting $FRIENDLY_NAME..."
-
-    buildclasspath
-    checkandrepairenv
-
-    $JAVACMD -cp ${CLASSPATH} $JAVA_OPTS \
-      -DconfigFile=conf/arbiter-wrapper.conf \
-      -Dorg.neo4j.server.properties="${NEO4J_CONFIG}/neo4j-server.properties" \
-      -Dorg.neo4j.cluster.logdirectory="${NEO4J_LOG}" \
-      -Dneo4j.home="${NEO4J_HOME}" \
-      org.neo4j.server.enterprise.StandaloneClusterClient  >> "$NEO4J_LOG/arbiter-console.log" 2>&1 & echo $! > "${PID_FILE}"
-    STARTED_PID=$( cat "$PID_FILE" )
-
-    printf " process [$STARTED_PID]... waiting for arbiter to be ready."
-
-    if kill -0 $STARTED_PID 2>/dev/null ; then
-      echo " OK."
-      exit 0
-    fi
-
-    echo " BAD."
-    echo "$FRIENDLY_NAME may have failed to start, please check the logs."
-    rm "$PID_FILE"
-    exit 1
-  else
-    echo "$FRIENDLY_NAME already running with pid $NEO4J_PID"
+  if [ -n "${NEO4J_PID}" ] ; then
+    echo "${FRIENDLY_NAME} is already running (pid ${NEO4J_PID})."
     exit 0
   fi
+
+  exitonnojava
+  checkjvmcompatibility
+
+  echo "Starting ${FRIENDLY_NAME}."
+
+  buildclasspath
+  checkclasspath
+  checkandrepairenv
+
+  CONSOLE_LOG="${NEO4J_LOG}/arbiter-console.log"
+  nohup "${JAVACMD}" -cp "${CLASSPATH}" ${JAVA_OPTS} -Dneo4j.home="${NEO4J_HOME}" -Dfile.encoding=UTF-8 \
+    org.neo4j.server.enterprise.StandaloneClusterClient \
+    >>"${CONSOLE_LOG}" 2>&1 &
+  echo "$!" >"${PID_FILE}"
+
+  sleep 5
+  checkstatus
+  if [ -z "${NEO4J_PID}" ] ; then
+    echo "Unable to start. See ${CONSOLE_LOG} for details."
+    rm "${PID_FILE}"
+    exit 1
+  fi
+
+  echo "Started."
+  echo "This instance is now joining the cluster. See ${CONSOLE_LOG} for current status."
 }
 
 console() {
   checkstatus
-
-  if [ -z $NEO4J_PID ] ; then
-    echo "Starting $FRIENDLY_NAME console-mode..."
-
-    exitonnojava
-    buildclasspath
-    checkandrepairenv
-
-    $JAVACMD -cp "${CLASSPATH}" $JAVA_OPTS -DconfigFile=conf/arbiter-wrapper.conf \
-	    -DconfigFile=conf/arbiter-wrapper.conf \
-      -Dorg.neo4j.server.properties="${NEO4J_CONFIG}/neo4j-server.properties" \
-	    -Dorg.neo4j.cluster.logdirectory="${NEO4J_LOG}" \
-      -Dneo4j.home=\"${NEO4J_HOME}\" \
-      org.neo4j.server.enterprise.StandaloneClusterClient
-  else
-    echo "$FRIENDLY_NAME already running with pid $NEO4J_PID"
+  if [ -n "${NEO4J_PID}" ] ; then
+    echo "${FRIENDLY_NAME} is already running (pid ${NEO4J_PID})."
     exit 1
   fi
+
+  exitonnojava
+  checkjvmcompatibility
+
+  echo "Starting ${FRIENDLY_NAME}."
+
+  buildclasspath
+  checkclasspath
+  checkandrepairenv
+
+  exec "${JAVACMD}" -cp "${CLASSPATH}" ${JAVA_OPTS} -Dneo4j.home="${NEO4J_HOME}" -Dfile.encoding=UTF-8 \
+    org.neo4j.server.enterprise.StandaloneClusterClient
 }
 
 showinfo() {
@@ -134,44 +132,35 @@ showinfo() {
   echo "CLASSPATH:         $CLASSPATH"
 }
 
-# END FUNCTIONS
-# BEGIN MAIN
-
 case "${1}" in
   console)
     console
-    exit 0
     ;;
 
   start)
     startit
-    exit 0
     ;;
 
   stop)
     stopit
-    exit 0
     ;;
 
   restart)
     stopit
     startit
-    exit 0
     ;;
 
   status)
     reportstatus
-    exit 0
     ;;
 
   info)
     showinfo
-    exit 0
     ;;
 
   *)
     echo "Usage: neo4j { start | stop | restart | status | info }"
-    exit 1;;
+    ;;
 esac
 
 exit $?
