Updates packaging to work with the new HA
* Removes functionality from coordinator scripts, replaced with a message
   noting their obsolesence.
* Updates licenses
* Leaves coordinator files in place because they will be necessary later
   for rolling upgrade functionality
* Updates configuration for the new settings

Authors: Anders Nawroth, Johan Svensson, Mattias Persson, Rickard Oberg, Chris Gioran

diff --git a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-coordinator-shell b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-coordinator-shell
--- a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-coordinator-shell
+++ b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-coordinator-shell
@@ -18,93 +18,5 @@
 # You should have received a copy of the GNU Affero General Public License
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 
-BASEDIR=`dirname "$0"`/..
-BASEDIR=`(cd "$BASEDIR"; pwd)`
-
-# OS specific support.  $var _must_ be set to either true or false.
-cygwin=false;
-darwin=false;
-case "`uname`" in
-  CYGWIN*) cygwin=true ;;
-  Darwin*) darwin=true
-           if [ -z "$JAVA_VERSION" ] ; then
-             JAVA_VERSION="CurrentJDK"
-           else
-             echo "Using Java version: $JAVA_VERSION"
-           fi
-           if [ -z "$JAVA_HOME" ] ; then
-             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
-           fi
-           ;;
-esac
-
-if [ -z "$JAVA_HOME" ] ; then
-  if [ -r /etc/gentoo-release ] ; then
-    JAVA_HOME=`java-config --jre-home`
-  fi
-fi
-
-# For Cygwin, ensure paths are in UNIX format before anything is touched
-if $cygwin ; then
-  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
-  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
-fi
-
-# If a specific java binary isn't specified search for the standard 'java' binary
-if [ -z "$JAVACMD" ] ; then
-  if [ -n "$JAVA_HOME"  ] ; then
-    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
-      # IBM's JDK on AIX uses strange locations for the executables
-      JAVACMD="$JAVA_HOME/jre/sh/java"
-    else
-      JAVACMD="$JAVA_HOME/bin/java"
-    fi
-  else
-    JAVACMD=`which java`
-  fi
-fi
-
-if [ ! -x "$JAVACMD" ] ; then
-  echo "Error: JAVA_HOME is not defined correctly."
-  echo "  We cannot execute $JAVACMD"
-  exit 1
-fi
-
-if [ -z "$REPO" ]
-then
-  REPO="$BASEDIR"/lib
-fi
-
-LIBRARY_JARS=""
-for jar in "$REPO"/*.jar
-do
-  LIBRARY_JARS="$LIBRARY_JARS":$jar
-done
-for jar in "$BASEDIR"/system/coordinator/lib/*.jar
-do
-  LIBRARY_JARS="$LIBRARY_JARS":$jar
-done
-# echo "$LIBRARY_JARS"
-
-CLASSPATH=$CLASSPATH_PREFIX${LIBRARY_JARS}
-
-EXTRA_JVM_ARGUMENTS=""
-
-# For Cygwin, switch paths to Windows format before running java
-if $cygwin; then
-  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
-  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
-  [ -n "$HOME" ] && HOME=`cygpath --path --windows "$HOME"`
-  [ -n "$BASEDIR" ] && BASEDIR=`cygpath --path --windows "$BASEDIR"`
-  [ -n "$REPO" ] && REPO=`cygpath --path --windows "$REPO"`
-fi
-
-exec "$JAVACMD" $JAVA_OPTS \
-  $EXTRA_JVM_ARGUMENTS \
-  -classpath "$CLASSPATH" \
-  -Dapp.name="neo4j-coordinator-shell" \
-  -Dapp.pid="$$" \
-  -Dapp.repo="$REPO" \
-  -Dbasedir="$BASEDIR" \
-  org.apache.zookeeper.ZooKeeperMain \
-  "$@"
+echo "The Coordinator functionality and corresponding scripts are no longer required for Neo4j HA operations since version 1.9"
+exit 1
