service script will now return immediately and direct users to logs in HA mode

diff --git a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
--- a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
+++ b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
@@ -198,12 +198,24 @@ startit() {
         -Dfile.encoding=UTF-8 \
         org.neo4j.server.Bootstrapper >> "${NEO4J_LOG}/console.log" 2>&1 & echo $! > "${PID_FILE}"
     fi
+
     STARTED_PID=$( cat "$PID_FILE" )
+
+    if [ "$org_neo4j_server_database_mode" = "HA" ] ; then
+      if kill -0 $STARTED_PID 2>/dev/null ; then
+        echo "HA instance started in process [$STARTED_PID]. Will be operational once connected to peers. See console log for status."
+        exit 0
+      else
+        echo "HA instance was unable to start. Please see console log "
+        rm "$PID_FILE"
+        exit 1
+      fi
+    fi
 
     echo -n "process [$STARTED_PID]"
 
-	if [ $WAIT = "true" ] ; then
-	echo -n "... waiting for server to be ready."
+	  if [ $WAIT = "true" ] ; then
+	    echo -n "... waiting for server to be ready."
 	    while kill -0 $STARTED_PID 2> /dev/null ; do
 	      ## wait for start, pick up the server listening on the port
 	      detectrunning
