Modified neo4j shell script to allow options for headless install and specifying install user on the command line.

diff --git a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
--- a/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
+++ b/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
@@ -75,11 +75,16 @@ NEO4J_SERVER_PORT=${org_neo4j_server_webserver_port:=7474}
 
 LAUNCHD_NAME="${LAUNCHD_NAME}.${NEO4J_SERVER_PORT}"
 
+HEADLESS=false
+
 if [ -z "${wrapper_user}" ]; then
   NEO4J_USER=`id -un`
 else
   NEO4J_USER=${wrapper_user}
 fi
+
+# Username to propose for neo4j user, can be overridden by -u USERNAME option
+DEFAULT_USER='neo4j'
 
 SCRIPT_NAME="${NEO4J_HOME}/bin/neo4j"
 SERVICE_NAME=${wrapper_ntservice_name:=neo4j-service}
@@ -287,7 +292,11 @@ installservice() {
     detectos
     findjava
     if [ ! -x "$JAVACMD" ] ; then
-      read -p "It was not possible to determine JAVA_HOME. Do you want to continue with the installation? [yN]" yn
+      if [[ $HEADLESS == false ]]; then
+        read -p "It was not possible to determine JAVA_HOME. Do you want to continue with the installation? [yN]" yn
+      else
+        $yn='y'
+      fi
       case $yn in
               [yY]* ) echo "WARNING: Alright, but $FRIENDLY_NAME will fail to launch until Java has been properly installed and configured."
               ;;
@@ -312,12 +321,20 @@ installservice() {
           if [[ $NEO4J_USER == $wrapper_user ]]; then 
             default_user=$wrapper_user
           else
-            default_user="neo4j"
+            default_user=$DEFAULT_USER
           fi
-          read -p "Graph-like power should be handled carefully. What user should run Neo4j? [$default_user] " proposed_user
+
+          if [[ $HEADLESS == false ]]; then
+            read -p "Graph-like power should be handled carefully. What user should run Neo4j? [$default_user] " proposed_user
+          fi
           proposed_user=${proposed_user:-$default_user}
+
           if ! `id $proposed_user &> /dev/null` ; then
-            read -p "User \"$proposed_user\" does not yet exist. Shall I create the account for you? [Yn]" yn
+            if [[ $HEADLESS == false ]]; then
+              read -p "User \"$proposed_user\" does not yet exist. Shall I create the account for you? [Yn]" yn
+            else
+              $yn="y"
+            fi
             case $yn in
               [Nn]* ) echo "WARNING: Alright, but Neo4j will fail to launch until that user has been created."
               set_user $proposed_user
@@ -362,7 +379,32 @@ showinfo() {
   echo "CLASSPATH:         $CLASSPATH"
 }
 
-case "$1" in
+# END FUNCTIONS
+# BEGIN MAIN
+
+# Parse option flags
+while getopts "u:h" opt; do
+  case $opt in
+    h)
+      echo "Running in headless (-h) mode" >&2
+      HEADLESS=true
+      ;;
+    u)
+      echo "Installing with user $OPTARG"
+      DEFAULT_USER=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+case "${!OPTIND}" in
   console)
     console
     ;;
